name: Android Unit Test With Telegram Notification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Unit tests
      run: bash ./gradlew test --stacktrace
      
    - name: send custom message
      uses: appleboy/telegram-action@master
      if: always()
      with:
        to: ${{ secrets.MESSAGEID }}
        token: ${{ secrets.BOTTOKEN }}
        message: |
          Commit Message: ${{ github.event.head_commit.message }}
          Commited Actor: ${{ github.actor }}
          Build Info: https://github.com/{{repo}}/commit/{{commit.sha}}/checks
          Build Status: ${{ job.status }}
