name: Unit Test with Debug APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Unit Test and Generate Debug APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Debug APK
      run: bash ./gradlew :app:assembleDebug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk

    - name: send custom message
      uses: appleboy/telegram-action@master
      if: success()
      with:
        to: ${{ secrets.MESSAGEID }}
        token: ${{ secrets.BOTTOKEN }}
        message: |
          Commit Message: ${{ github.event.head_commit.message }}
          Commited Actor: ${{ github.actor }}
          Build Info: https://github.com/${{github.repository}}/commit/${{github.sha}}/checks
          Build Status: ${{ job.status }}
        document: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk

    - name: send custom message
      uses: appleboy/telegram-action@master
      if: failure()
      with:
        to: ${{ secrets.MESSAGEID }}
        token: ${{ secrets.BOTTOKEN }}
        message: |
          Commit Message: ${{ github.event.head_commit.message }}
          Commited Actor: ${{ github.actor }}
          Build Info: https://github.com/${{github.repository}}/commit/${{github.sha}}/checks
          Build Status: ${{ job.status }}
